import { db } from "./db";
import { products } from "@shared/schema";

const seedProducts = [
  {
    slug: "royal-heritage-gold-necklace",
    name: "Royal Heritage Gold Necklace",
    category: "Gold",
    metalType: "Gold",
    purity: "22K",
    weight: "22g",
    price: 125000,
    originalPrice: 140000,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=800",
    images: [],
    gallery: [],
    videos: [],
    stockStatus: "In Stock",
    shortDescription: "A masterpiece of heritage craftsmanship",
    description: "A masterpiece of craftsmanship, this heritage gold necklace features intricate detailing inspired by royal courts. Perfect for weddings and special occasions.",
    specifications: { Brand: "Twinkle Star", Collection: "Royal Heritage", Gender: "Women", Occasion: "Wedding" },
    shippingInfo: "Free insured shipping across India. Delivery within 5-7 business days.",
    isFeatured: true,
    isNew: true,
    tags: ["Bestseller", "Trending"],
    festivalOffer: null,
  },
  {
    slug: "solitaire-diamond-ring",
    name: "Solitaire Diamond Ring",
    category: "Diamond",
    metalType: "Diamond",
    purity: "18K Gold / VVS1 Diamond",
    weight: "4g",
    price: 85000,
    originalPrice: null,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=800",
    images: [],
    gallery: [],
    videos: [],
    stockStatus: "In Stock",
    shortDescription: "Symbol of eternal love",
    description: "An exquisite solitaire diamond ring set in 18K white gold. The symbol of eternal love and sophistication.",
    specifications: { Brand: "Twinkle Star", Collection: "Eternal", Gender: "Unisex", Stone: "VVS1 Diamond" },
    shippingInfo: "Free insured shipping across India.",
    isFeatured: true,
    isNew: true,
    tags: ["Wedding", "Engagement"],
    festivalOffer: null,
  },
  {
    slug: "swiss-gold-bar-24k",
    name: "Swiss Gold Bar 24K",
    category: "Bars",
    metalType: "Gold",
    purity: "999.9",
    weight: "10g",
    price: 65000,
    originalPrice: null,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1610375461246-83df859d849d?auto=format&fit=crop&q=80&w=800",
    images: [],
    gallery: [],
    videos: [],
    stockStatus: "In Stock",
    shortDescription: "Investment grade 24K gold",
    description: "Investment grade 24K gold bar with Swiss certification. Secure your future with pure gold.",
    specifications: { Brand: "Swiss Certified", Purity: "999.9", Type: "Investment Gold" },
    shippingInfo: "Secure insured delivery.",
    isFeatured: true,
    isNew: false,
    tags: ["Investment", "Gift"],
    festivalOffer: null,
  },
  {
    slug: "lakshmi-gold-coin",
    name: "Lakshmi Gold Coin",
    category: "Coins",
    metalType: "Gold",
    purity: "24K",
    weight: "5g",
    price: 32000,
    originalPrice: null,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1624365168968-f283d506c6b6?auto=format&fit=crop&q=80&w=800",
    images: [],
    gallery: [],
    videos: [],
    stockStatus: "In Stock",
    shortDescription: "Auspicious Lakshmi coin",
    description: "Auspicious 24K gold coin featuring Goddess Lakshmi. Perfect for gifting and festivals.",
    specifications: { Brand: "Twinkle Star", Purity: "24K", Occasion: "Festival" },
    shippingInfo: "Free shipping on orders above Rs 10,000.",
    isFeatured: true,
    isNew: false,
    tags: ["Festival", "Gift", "Diwali"],
    festivalOffer: "Diwali Special - Free Silver Coin!",
  },
  {
    slug: "elegant-silver-anklet",
    name: "Elegant Silver Anklet",
    category: "Silver",
    metalType: "Silver",
    purity: "925 Sterling",
    weight: "15g",
    price: 4500,
    originalPrice: 5000,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=800",
    images: [],
    gallery: [],
    videos: [],
    stockStatus: "In Stock",
    shortDescription: "Elegant sterling silver anklet",
    description: "Beautiful sterling silver anklet with intricate design. Perfect for everyday wear.",
    specifications: { Brand: "Twinkle Star", Purity: "925", Gender: "Women" },
    shippingInfo: "Free shipping.",
    isFeatured: false,
    isNew: true,
    tags: ["Daily Wear", "Silver"],
    festivalOffer: null,
  },
  {
    slug: "diamond-tennis-bracelet",
    name: "Diamond Tennis Bracelet",
    category: "Diamond",
    metalType: "Diamond",
    purity: "18K White Gold / VS Diamonds",
    weight: "12g",
    price: 250000,
    originalPrice: 280000,
    currency: "INR",
    image: "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&q=80&w=800",
    images: [],
    gallery: [],
    videos: [],
    stockStatus: "Limited",
    shortDescription: "Stunning diamond tennis bracelet",
    description: "A stunning diamond tennis bracelet featuring VS clarity diamonds set in 18K white gold.",
    specifications: { Brand: "Twinkle Star", Collection: "Luxe", Gender: "Women", Stone: "VS Diamonds" },
    shippingInfo: "Free insured shipping.",
    isFeatured: true,
    isNew: false,
    tags: ["Luxury", "Wedding"],
    festivalOffer: null,
  },
];

export async function seedDatabase() {
  try {
    const existingProducts = await db.select().from(products);
    if (existingProducts.length > 0) {
      console.log("Database already has products, skipping seed");
      return;
    }

    for (const product of seedProducts) {
      await db.insert(products).values(product);
    }
    console.log(`Seeded ${seedProducts.length} products`);
  } catch (error) {
    console.error("Error seeding database:", error);
  }
}
